[project]
name = "are-summarizer"
version = "0.1.0"
description = "Placeholder pipeline for transcription and summarization."
readme = "README.md"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
